Repository popi-official/popi-user-server, pull requests merged in 2025-05, with the labels that each got.

#15 chore: jacoco, sonarqube(cloud) 세팅
  .github/workflows/popi-ci.yml
  build.gradle
  popi-api-gateway/src/test/resources/application.yml
  popi-auth-service/build.gradle
  popi-auth-service/src/test/resources/application.yml
  popi-common/src/main/java/com/lgcns/PopiCommonApplication.java
  popi-common/src/test/java/com/lgcns/PopiCommonApplicationTests.java
  popi-eureka-server/src/test/resources/application.yml
Labels: ⚙️ chore

#17 feat: API Gateway JWT 인증 필터 구현
  build.gradle
  popi-api-gateway/build.gradle
  popi-api-gateway/src/main/java/com/lgcns/PopiApiGatewayApplication.java
  popi-api-gateway/src/main/java/com/lgcns/common/constants/SecurityConstants.java
  popi-api-gateway/src/main/java/com/lgcns/domain/MemberRole.java
  popi-api-gateway/src/main/java/com/lgcns/dto/AccessTokenDto.java
  popi-api-gateway/src/main/java/com/lgcns/error/ErrorResponse.java
  popi-api-gateway/src/main/java/com/lgcns/error/FailResponse.java
  popi-api-gateway/src/main/java/com/lgcns/error/exception/GatewayAuthErrorCode.java
  popi-api-gateway/src/main/java/com/lgcns/filter/JwtAuthenticationFilter.java
  popi-api-gateway/src/main/java/com/lgcns/service/JwtTokenService.java
  popi-api-gateway/src/main/java/com/lgcns/util/JwtUtil.java
  popi-api-gateway/src/test/resources/application.yml
  popi-auth-service/src/main/java/com/lgcns/config/SwaggerConfig.java
Labels: ✨ feature

#19 chore: k8s 환경 구축
  .github/workflows/popi-ci.yml
  .gitignore
  k8s/api-gateway/configmap.yml
  k8s/api-gateway/deploy.yml
  k8s/auth/configmap.yml
  k8s/auth/deploy.yml
  popi-api-gateway/Dockerfile
  popi-api-gateway/build.gradle
  popi-api-gateway/src/main/resources/application-local.yml
  popi-api-gateway/src/main/resources/application.yml
  popi-api-gateway/src/test/resources/application.yml
  popi-auth-service/Dockerfile
  popi-auth-service/build.gradle
  popi-auth-service/src/main/resources/application-local.yml
  popi-auth-service/src/main/resources/application.yml
  popi-auth-service/src/test/resources/application.yml
  popi-common/build.gradle
  popi-config-server/build.gradle
  popi-config-server/src/main/java/com/lgcns/PopiConfigServerApplication.java
  popi-config-server/src/main/resources/application.yml
  popi-config-server/src/test/java/com/lgcns/PopiConfigServerApplicationTests.java
  popi-eureka-server/build.gradle
  popi-eureka-server/src/main/resources/application.yml
  popi-eureka-server/src/test/resources/application.yml
  settings.gradle
Labels: ⚙️ chore

#20 chore: GitOps 기반 Helm 관리로 전환
  k8s/api-gateway/configmap.yml
  k8s/api-gateway/deploy.yml
  k8s/auth/configmap.yml
  k8s/auth/deploy.yml
  popi-api-gateway/src/main/resources/application-local.yml
  popi-auth-service/src/main/resources/application-local.yml
Labels: ⚙️ chore

#21 feat: 회원 마이크로서비스 초기 세팅
  popi-api-gateway/src/main/resources/application-local.yml
  popi-auth-service/src/main/resources/application-local.yml
  popi-member-service/Dockerfile
  popi-member-service/build.gradle
  popi-member-service/src/main/java/com/lgcns/PopiMemberServiceApplication.java
  popi-member-service/src/main/java/com/lgcns/config/SwaggerConfig.java
  popi-member-service/src/main/resources/application-local.yml
  popi-member-service/src/test/java/com/lgcns/PopiMemberServiceApplicationTests.java
  popi-member-service/src/test/resources/application.yml
  settings.gradle
Labels: ✨ feature

#23 chore: Gradle 루트 프로젝트 이름 변경
  settings.gradle
Labels: ⚙️ chore

#26 feat: 소셜 로그인 시 SDK 방식을 사용하도록 변경
  popi-auth-service/src/main/java/com/lgcns/client/GoogleOauthClient.java
  popi-auth-service/src/main/java/com/lgcns/client/KakaoOauthClient.java
  popi-auth-service/src/main/java/com/lgcns/config/FeignConfig.java
  popi-auth-service/src/main/java/com/lgcns/constants/SecurityConstants.java
  popi-auth-service/src/main/java/com/lgcns/controller/AuthController.java
  popi-auth-service/src/main/java/com/lgcns/domain/OauthProvider.java
  popi-auth-service/src/main/java/com/lgcns/dto/request/AuthCodeRequest.java
  popi-auth-service/src/main/java/com/lgcns/dto/request/IdTokenRequest.java
  popi-auth-service/src/main/java/com/lgcns/dto/response/IdTokenResponse.java
  popi-auth-service/src/main/java/com/lgcns/infra/jwt/JwtProperties.java
  popi-auth-service/src/main/java/com/lgcns/infra/oidc/OidcProperties.java
  popi-auth-service/src/main/java/com/lgcns/infra/properties/PropertiesConfig.java
  popi-auth-service/src/main/java/com/lgcns/infra/redis/RedisConfig.java
  popi-auth-service/src/main/java/com/lgcns/infra/redis/RedisProperties.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthService.java
  popi-auth-service/src/main/java/com/lgcns/service/GoogleService.java
  popi-auth-service/src/main/java/com/lgcns/service/IdTokenVerifier.java
  popi-auth-service/src/main/java/com/lgcns/service/KakaoService.java
  popi-auth-service/src/main/java/com/lgcns/util/JwtUtil.java
  popi-auth-service/src/main/resources/application-local.yml
  popi-auth-service/src/test/resources/application.yml
Labels: ✨ feature

#29 fix: Google audience 설정 키명 수정
  popi-auth-service/src/main/resources/application-local.yml
Labels: 🐛 bug/error

#32 chore: Common 모듈 JPA 의존성 제거
  popi-auth-service/build.gradle
  popi-common/build.gradle
  popi-member-service/build.gradle
  popi-reservation-service/build.gradle
Labels: ⚙️ chore

#34 feat: Domain 모듈 생성
  popi-auth-service/build.gradle
  popi-auth-service/src/main/java/com/lgcns/domain/Member.java
  popi-common/build.gradle
  popi-domain/build.gradle
  popi-domain/src/main/java/com/lgcns/config/JpaAuditingConfig.java
  popi-domain/src/main/java/com/lgcns/config/QueryDslConfig.java
  popi-domain/src/main/java/com/lgcns/entity/BaseTimeEntity.java
  popi-member-service/build.gradle
  popi-member-service/src/main/java/com/lgcns/domain/Member.java
  popi-reservation-service/build.gradle
  settings.gradle
Labels: ✨ feature

#30 chore: 예약/인증 서비스 Redis 논리 DB 분리
  popi-auth-service/src/main/resources/application-local.yml
  popi-reservation-service/build.gradle
  popi-reservation-service/src/main/java/com/lgcns/PopiReservationServiceApplication.java
  popi-reservation-service/src/main/java/com/lgcns/config/SwaggerConfig.java
  popi-reservation-service/src/main/java/com/lgcns/infra/properties/PropertiesConfig.java
  popi-reservation-service/src/main/java/com/lgcns/infra/redis/RedisConfig.java
  popi-reservation-service/src/main/java/com/lgcns/infra/redis/RedisProperties.java
  popi-reservation-service/src/main/resources/application-local.yml
  popi-reservation-service/src/test/java/com/lgcns/PopiReservationServiceApplicationTests.java
  popi-reservation-service/src/test/resources/application.yml
Labels: ⚙️ chore

#31 chore: 팝업 마이크로서비스 초기 세팅
  popi-api-gateway/src/main/resources/application-local.yml
  popi-popup-service/Dockerfile
  popi-popup-service/build.gradle
  popi-popup-service/src/main/java/com/lgcns/PopiPopupServiceApplication.java
  popi-popup-service/src/main/java/com/lgcns/config/SwaggerConfig.java
  popi-popup-service/src/main/resources/application-local.yml
  popi-popup-service/src/test/java/com/lgcns/PopiPopupServiceApplicationTests.java
  popi-reservation-service/build.gradle
  settings.gradle
Labels: ⚙️ chore

#33 chore: 알림 마이크로서비스 초기 세팅
  popi-api-gateway/src/main/resources/application-local.yml
  popi-notification-service/Dockerfile
  popi-notification-service/build.gradle
  popi-notification-service/src/main/java/com/lgcns/PopiNotificationServiceApplication.java
  popi-notification-service/src/main/java/com/lgcns/config/SwaggerConfig.java
  popi-notification-service/src/main/resources/application-local.yml
  popi-notification-service/src/test/java/com/lgcns/PopiNotificationServiceApplicationTests.java
  settings.gradle
Labels: ⚙️ chore

#35 feat: 로그아웃 기능 구현
  .github/workflows/popi-ci.yml
  docker-compose-test.yml
  popi-api-gateway/src/main/resources/application-local.yml
  popi-auth-service/src/main/java/com/lgcns/config/SwaggerConfig.java
  popi-auth-service/src/main/java/com/lgcns/config/WebSecurityConfig.java
  popi-auth-service/src/main/java/com/lgcns/controller/AuthController.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthService.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthServiceImpl.java
  popi-auth-service/src/main/java/com/lgcns/util/CookieUtil.java
  popi-auth-service/src/test/java/com/lgcns/service/AuthServiceTest.java
  popi-auth-service/src/test/resources/application.yml
Labels: ✨ feature

#36 feat: 회원탈퇴 기능 구현
  popi-api-gateway/src/main/resources/application-local.yml
  popi-auth-service/src/main/java/com/lgcns/controller/AuthController.java
  popi-auth-service/src/main/java/com/lgcns/domain/Member.java
  popi-auth-service/src/main/java/com/lgcns/exception/MemberErrorCode.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthService.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthServiceImpl.java
  popi-auth-service/src/test/java/com/lgcns/service/AuthServiceTest.java
Labels: ✨ feature

#37 fix: 예약 서비스 SwaggerConfig 수정
  popi-reservation-service/src/main/java/com/lgcns/config/SwaggerConfig.java
Labels: 🐛 bug/error

#38 fix: 소셜 로그인 API JSON 바인딩 실패 오류 수정
  popi-auth-service/src/main/java/com/lgcns/controller/AuthController.java
Labels: 🐛 bug/error

#39 chore: 공통 응답 포맷 제외용 커스텀 어노테이션 추가
  popi-common/src/main/java/com/lgcns/annotation/RawResponse.java
  popi-common/src/main/java/com/lgcns/response/GlobalResponseAdvice.java
Labels: ⚙️ chore

#40 feat: Register Token 기반 회원가입 기능 구현
  popi-api-gateway/src/main/resources/application-local.yml
  popi-auth-service/src/main/java/com/lgcns/controller/AuthController.java
  popi-auth-service/src/main/java/com/lgcns/domain/Member.java
  popi-auth-service/src/main/java/com/lgcns/dto/RegisterTokenDto.java
  popi-auth-service/src/main/java/com/lgcns/dto/request/RegisterTokenRequest.java
  popi-auth-service/src/main/java/com/lgcns/dto/response/SocialLoginResponse.java
  popi-auth-service/src/main/java/com/lgcns/exception/AuthErrorCode.java
  popi-auth-service/src/main/java/com/lgcns/infra/jwt/JwtProperties.java
  popi-auth-service/src/main/java/com/lgcns/repository/MemberRepository.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthService.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthServiceImpl.java
  popi-auth-service/src/main/java/com/lgcns/service/JwtTokenService.java
  popi-auth-service/src/main/java/com/lgcns/util/JwtUtil.java
  popi-auth-service/src/main/resources/application-local.yml
  popi-auth-service/src/test/java/com/lgcns/service/AuthServiceTest.java
  popi-auth-service/src/test/resources/application.yml
Labels: ✨ feature

#43 feat: Feign 클라이언트용 커스텀 예외 디코딩 로직 구현
  build.gradle
  popi-common/build.gradle
  popi-common/src/main/java/com/lgcns/config/FeignConfig.java
  popi-common/src/main/java/com/lgcns/error/feign/FeignErrorCode.java
  popi-common/src/main/java/com/lgcns/error/feign/FeignErrorDecoder.java
Labels: ✨ feature

#41 feat: 예약 가능 날짜 조회 기능 구현
  build.gradle
  popi-domain/build.gradle
  popi-reservation-service/build.gradle
  popi-reservation-service/src/main/java/com/lgcns/client/ManagerServiceClient.java
  popi-reservation-service/src/main/java/com/lgcns/client/dto/DailyReservation.java
  popi-reservation-service/src/main/java/com/lgcns/client/dto/MonthlyReservationResponse.java
  popi-reservation-service/src/main/java/com/lgcns/client/dto/TimeSlot.java
  popi-reservation-service/src/main/java/com/lgcns/controller/MemberReservationController.java
  popi-reservation-service/src/main/java/com/lgcns/domain/MemberReservation.java
  popi-reservation-service/src/main/java/com/lgcns/dto/response/AvailableDateResponse.java
  popi-reservation-service/src/main/java/com/lgcns/dto/response/DailyReservationCountResponse.java
  popi-reservation-service/src/main/java/com/lgcns/dto/response/HourlyReservationCount.java
  popi-reservation-service/src/main/java/com/lgcns/dto/response/ReservableDate.java
  popi-reservation-service/src/main/java/com/lgcns/dto/response/ReservableTime.java
  popi-reservation-service/src/main/java/com/lgcns/exception/MemberReservationErrorCode.java
  popi-reservation-service/src/main/java/com/lgcns/repository/MemberReservationRepository.java
  popi-reservation-service/src/main/java/com/lgcns/repository/MemberReservationRepositoryCustom.java
  popi-reservation-service/src/main/java/com/lgcns/repository/MemberReservationRepositoryImpl.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationService.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationServiceImpl.java
  popi-reservation-service/src/main/resources/application-local.yml
  popi-reservation-service/src/test/java/com/lgcns/PopiReservationServiceApplicationTests.java
  popi-reservation-service/src/test/java/com/lgcns/WireMockIntegrationTest.java
  popi-reservation-service/src/test/java/com/lgcns/service/MemberReservationServiceTest.java
  popi-reservation-service/src/test/resources/application-test.yml
Labels: ✨ feature

#49 chore: 결제 마이크로서비스 초기 세팅
  popi-api-gateway/src/main/resources/application-local.yml
  popi-payment-service/Dockerfile
  popi-payment-service/build.gradle
  popi-payment-service/src/main/java/com/lgcns/PopiPaymentServiceApplication.java
  popi-payment-service/src/main/java/com/lgcns/config/SwaggerConfig.java
  popi-payment-service/src/main/resources/application-local.yml
  popi-payment-service/src/test/java/com/lgcns/PopiPaymentServiceApplicationTests.java
  popi-payment-service/src/test/resources/application-test.yml
  settings.gradle
Labels: ⚙️ chore

#45 refactor: 인증 서비스 내 회원 도메인 로직 제거 및 회원 서비스로 책임 분리
  build.gradle
  popi-api-gateway/src/main/resources/application-local.yml
  popi-auth-service/build.gradle
  popi-auth-service/src/main/java/com/lgcns/client/MemberServiceClient.java
  popi-auth-service/src/main/java/com/lgcns/domain/Member.java
  popi-auth-service/src/main/java/com/lgcns/domain/OauthInfo.java
  popi-auth-service/src/main/java/com/lgcns/dto/AccessTokenDto.java
  popi-auth-service/src/main/java/com/lgcns/dto/request/MemberRegisterRequest.java
  popi-auth-service/src/main/java/com/lgcns/exception/AuthErrorCode.java
  popi-auth-service/src/main/java/com/lgcns/exception/MemberErrorCode.java
  popi-auth-service/src/main/java/com/lgcns/externalApi/AuthController.java
  popi-auth-service/src/main/java/com/lgcns/internalApi/AuthInternalController.java
  popi-auth-service/src/main/java/com/lgcns/repository/MemberRepository.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthService.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthServiceImpl.java
  popi-auth-service/src/main/java/com/lgcns/service/JwtTokenService.java
  popi-auth-service/src/main/java/com/lgcns/util/JwtUtil.java
  popi-auth-service/src/main/resources/application-local.yml
  popi-auth-service/src/test/java/com/lgcns/PopiAuthServiceApplicationTests.java
  popi-auth-service/src/test/java/com/lgcns/WireMockIntegrationTest.java
  popi-auth-service/src/test/java/com/lgcns/service/AuthServiceTest.java
  popi-auth-service/src/test/resources/application-test.yml
  popi-common/src/main/java/com/lgcns/dto/request/MemberInternalRegisterRequest.java
  popi-common/src/main/java/com/lgcns/dto/request/MemberOauthInfoRequest.java
  popi-common/src/main/java/com/lgcns/dto/response/MemberInternalInfoResponse.java
  popi-common/src/main/java/com/lgcns/dto/response/MemberInternalRegisterResponse.java
  popi-common/src/main/java/com/lgcns/enums/MemberAge.java
  popi-common/src/main/java/com/lgcns/enums/MemberGender.java
  popi-common/src/main/java/com/lgcns/enums/MemberRole.java
  popi-common/src/main/java/com/lgcns/enums/MemberStatus.java
  popi-common/src/main/java/com/lgcns/util/CookieUtil.java
  popi-member-service/build.gradle
  popi-member-service/src/main/java/com/lgcns/client/AuthServiceClient.java
  popi-member-service/src/main/java/com/lgcns/domain/Member.java
  popi-member-service/src/main/java/com/lgcns/domain/MemberAge.java
  popi-member-service/src/main/java/com/lgcns/domain/MemberGender.java
  popi-member-service/src/main/java/com/lgcns/domain/MemberRole.java
  popi-member-service/src/main/java/com/lgcns/domain/MemberStatus.java
  popi-member-service/src/main/java/com/lgcns/dto/response/MemberInfoResponse.java
  popi-member-service/src/main/java/com/lgcns/exception/MemberErrorCode.java
  popi-member-service/src/main/java/com/lgcns/externalApi/MemberController.java
  popi-member-service/src/main/java/com/lgcns/internalApi/MemberInternalController.java
  popi-member-service/src/main/java/com/lgcns/repository/MemberRepository.java
  popi-member-service/src/main/java/com/lgcns/service/MemberService.java
  popi-member-service/src/main/java/com/lgcns/service/MemberServiceImpl.java
  popi-member-service/src/main/resources/application-local.yml
  popi-member-service/src/test/java/com/lgcns/DatabaseCleaner.java
  popi-member-service/src/test/java/com/lgcns/IntegrationTest.java
  popi-member-service/src/test/java/com/lgcns/PopiMemberServiceApplicationTests.java
  popi-member-service/src/test/java/com/lgcns/service/MemberServiceTest.java
  popi-member-service/src/test/resources/application-test.yml
  popi-member-service/src/test/resources/application.yml
Labels: ♻️ refactor

#46 feat: 팝업 리스트 조회 기능 구현
  popi-popup-service/src/main/java/com/lgcns/client/ManagerServiceClient.java
  popi-popup-service/src/main/java/com/lgcns/config/FeignConfig.java
  popi-popup-service/src/main/java/com/lgcns/dto/popup/response/PopupInfoResponse.java
  popi-popup-service/src/main/java/com/lgcns/externalApi/ItemController.java
  popi-popup-service/src/main/java/com/lgcns/externalApi/PopupController.java
  popi-popup-service/src/main/java/com/lgcns/service/popup/PopupService.java
  popi-popup-service/src/main/java/com/lgcns/service/popup/PopupServiceImpl.java
  popi-popup-service/src/main/resources/application-local.yml
  popi-popup-service/src/test/java/com/lgcns/PopiPopupServiceApplicationTests.java
  popi-popup-service/src/test/java/com/lgcns/WireMockIntegrationTest.java
  popi-popup-service/src/test/java/com/lgcns/service/PopupServiceTest.java
  popi-popup-service/src/test/resources/application-test.yml
  popi-reservation-service/src/main/java/com/lgcns/externalApi/MemberReservationController.java
Labels: ✨ feature

#50 chore: 회원 서비스 flyway 설정
  popi-member-service/build.gradle
  popi-member-service/src/main/resources/application-local.yml
  popi-member-service/src/main/resources/db/migration/V1__init.sql
  popi-member-service/src/test/resources/application-test.yml
Labels: ⚙️ chore

#47 feat: 상품 검색 기능 구현
  popi-popup-service/src/main/java/com/lgcns/client/ManagerServiceClient.java
  popi-popup-service/src/main/java/com/lgcns/externalApi/ItemController.java
  popi-popup-service/src/main/java/com/lgcns/service/item/ItemService.java
  popi-popup-service/src/main/java/com/lgcns/service/item/ItemServiceImpl.java
  popi-popup-service/src/main/resources/application-local.yml
  popi-popup-service/src/test/java/com/lgcns/WireMockIntegrationTest.java
  popi-popup-service/src/test/java/com/lgcns/service/ItemServiceTest.java
  popi-popup-service/src/test/resources/application-test.yml
Labels: ✨ feature

#48 feat: 예약 후 설문지 조회 구현
  popi-reservation-service/src/main/java/com/lgcns/client/ManagerServiceClient.java
  popi-reservation-service/src/main/java/com/lgcns/dto/response/SurveyChoiceResponse.java
  popi-reservation-service/src/main/java/com/lgcns/dto/response/SurveyOption.java
  popi-reservation-service/src/main/java/com/lgcns/externalApi/MemberReservationController.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationService.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationServiceImpl.java
  popi-reservation-service/src/main/resources/application-local.yml
  popi-reservation-service/src/test/java/com/lgcns/WireMockIntegrationTest.java
  popi-reservation-service/src/test/java/com/lgcns/service/MemberReservationServiceTest.java
  popi-reservation-service/src/test/resources/application-test.yml
Labels: ✨ feature

#51 chore: 예약 서비스 flyway 설정
  popi-reservation-service/build.gradle
  popi-reservation-service/src/main/java/com/lgcns/domain/MemberReservation.java
  popi-reservation-service/src/main/resources/application-local.yml
  popi-reservation-service/src/main/resources/db/migration/V1__init.sql
  popi-reservation-service/src/test/resources/application-test.yml
Labels: ⚙️ chore

#54 fix: 예약 서비스 flyway 오류 수정
  popi-reservation-service/src/main/resources/db/migration/V1__init.sql
Labels: 🐛 bug/error

#52 feat: 팝업 검색 기능 구현
  popi-popup-service/src/main/java/com/lgcns/client/ManagerServiceClient.java
  popi-popup-service/src/main/java/com/lgcns/externalApi/PopupController.java
  popi-popup-service/src/main/java/com/lgcns/service/popup/PopupService.java
  popi-popup-service/src/main/java/com/lgcns/service/popup/PopupServiceImpl.java
  popi-popup-service/src/test/java/com/lgcns/service/PopupServiceTest.java
Labels: ✨ feature

#58 feat: 마이페이지 예약 목록 조회 구현
  popi-reservation-service/src/main/java/com/lgcns/client/managerClient/ManagerServiceClient.java
  popi-reservation-service/src/main/java/com/lgcns/client/managerClient/dto/request/PopupIdsRequest.java
  popi-reservation-service/src/main/java/com/lgcns/client/managerClient/dto/response/DailyReservation.java
  popi-reservation-service/src/main/java/com/lgcns/client/managerClient/dto/response/MonthlyReservationResponse.java
  popi-reservation-service/src/main/java/com/lgcns/client/managerClient/dto/response/ReservationPopupInfoResponse.java
  popi-reservation-service/src/main/java/com/lgcns/client/managerClient/dto/response/TimeSlot.java
  popi-reservation-service/src/main/java/com/lgcns/dto/response/ReservationDetailResponse.java
  popi-reservation-service/src/main/java/com/lgcns/externalApi/MemberReservationController.java
  popi-reservation-service/src/main/java/com/lgcns/repository/MemberReservationRepository.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationService.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationServiceImpl.java
  popi-reservation-service/src/test/java/com/lgcns/service/MemberReservationServiceTest.java
Labels: ✨ feature

#57 feat: 예약 신청/취소 기능 구현
  popi-common/src/main/java/com/lgcns/dto/response/MemberInternalInfoResponse.java
  popi-member-service/src/main/java/com/lgcns/service/MemberServiceImpl.java
  popi-member-service/src/test/java/com/lgcns/service/MemberServiceTest.java
  popi-popup-service/src/main/java/com/lgcns/client/ManagerServiceClient.java
  popi-popup-service/src/main/java/com/lgcns/client/PopupIdsRequest.java
  popi-popup-service/src/main/java/com/lgcns/service/PopupServiceImpl.java
  popi-popup-service/src/test/java/com/lgcns/service/PopupServiceTest.java
  popi-reservation-service/build.gradle
  popi-reservation-service/src/main/java/com/lgcns/PopiReservationServiceApplication.java
  popi-reservation-service/src/main/java/com/lgcns/client/managerClient/ManagerServiceClient.java
  popi-reservation-service/src/main/java/com/lgcns/client/managerClient/dto/response/ReservationInfoResponse.java
  popi-reservation-service/src/main/java/com/lgcns/client/memberClient/MemberServiceClient.java
  popi-reservation-service/src/main/java/com/lgcns/domain/MemberReservation.java
  popi-reservation-service/src/main/java/com/lgcns/domain/MemberReservationStatus.java
  popi-reservation-service/src/main/java/com/lgcns/event/dto/MemberReservationUpdateEvent.java
  popi-reservation-service/src/main/java/com/lgcns/event/handler/MemberReservationUpdateEventHandler.java
  popi-reservation-service/src/main/java/com/lgcns/exception/MemberReservationErrorCode.java
  popi-reservation-service/src/main/java/com/lgcns/externalApi/MemberReservationController.java
  popi-reservation-service/src/main/java/com/lgcns/infra/redis/RedisConfig.java
  popi-reservation-service/src/main/java/com/lgcns/repository/MemberReservationRepository.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationService.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationServiceImpl.java
  popi-reservation-service/src/main/resources/application-local.yml
  popi-reservation-service/src/main/resources/db/migration/V1_1__alter_member_reservation_table_add_column.sql
  popi-reservation-service/src/test/java/com/lgcns/DatabaseCleaner.java
  popi-reservation-service/src/test/java/com/lgcns/service/MemberReservationMockTest.java
  popi-reservation-service/src/test/java/com/lgcns/service/MemberReservationServiceTest.java
  popi-reservation-service/src/test/resources/application-test.yml
Labels: ✨ feature

#64 feat: Internal 오늘 예약자 수 조회 API 구현
  popi-api-gateway/src/main/resources/application-local.yml
  popi-reservation-service/src/main/java/com/lgcns/dto/response/DailyMemberReservationCountResponse.java
  popi-reservation-service/src/main/java/com/lgcns/internalApi/MemberReservationInternalController.java
  popi-reservation-service/src/main/java/com/lgcns/repository/MemberReservationRepositoryCustom.java
  popi-reservation-service/src/main/java/com/lgcns/repository/MemberReservationRepositoryImpl.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationService.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationServiceImpl.java
  popi-reservation-service/src/test/java/com/lgcns/service/MemberReservationServiceTest.java
Labels: ✨ feature

#61 feat: 결제 검증 로직 구현
  popi-payment-service/build.gradle
  popi-payment-service/src/main/java/com/lgcns/domain/Payment.java
  popi-payment-service/src/main/java/com/lgcns/exception/PaymentErrorCode.java
  popi-payment-service/src/main/java/com/lgcns/externalApi/PaymentController.java
  popi-payment-service/src/main/java/com/lgcns/infra/config/IamportClientConfig.java
  popi-payment-service/src/main/java/com/lgcns/infra/iamport/IamportProperties.java
  popi-payment-service/src/main/java/com/lgcns/infra/properties/PropertiesConfig.java
  popi-payment-service/src/main/java/com/lgcns/repository/PaymentRepository.java
  popi-payment-service/src/main/java/com/lgcns/service/PaymentService.java
  popi-payment-service/src/main/java/com/lgcns/service/PaymentServiceImpl.java
  popi-payment-service/src/main/resources/application-local.yml
  popi-payment-service/src/test/java/com/lgcns/service/PaymentServiceTest.java
Labels: ✨ feature

#67 chore: 회원 서비스 ddl-auto 옵션을 validate로 변경
  popi-member-service/src/main/resources/application-local.yml
Labels: ⚙️ chore

#71 fix: 예약 서비스 RewritePath 필터 경로 매핑 수정
  popi-api-gateway/src/main/resources/application-local.yml
Labels: 🐛 bug/error

#70 feat: 설문지 답변 등록 엔드포인트 구현
  popi-api-gateway/src/main/resources/application-local.yml
  popi-reservation-service/src/main/java/com/lgcns/dto/request/SurveyChoiceRequest.java
  popi-reservation-service/src/main/java/com/lgcns/exception/MemberReservationErrorCode.java
  popi-reservation-service/src/main/java/com/lgcns/externalApi/MemberReservationController.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationService.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationServiceImpl.java
  popi-reservation-service/src/test/java/com/lgcns/service/MemberReservationServiceTest.java
Labels: ✨ feature

#69 feat: 결제 성공 시 Kafka로 상품 구매 메시지 발행 기능 구현
  docker-compose-kafka.yml
  popi-payment-service/build.gradle
  popi-payment-service/src/main/java/com/lgcns/domain/Payment.java
  popi-payment-service/src/main/java/com/lgcns/domain/PaymentItem.java
  popi-payment-service/src/main/java/com/lgcns/kafka/config/KafkaProducerConfig.java
  popi-payment-service/src/main/java/com/lgcns/kafka/message/ItemPurchasedMessage.java
  popi-payment-service/src/main/java/com/lgcns/kafka/producer/ItemPurchasedProducer.java
  popi-payment-service/src/main/java/com/lgcns/service/PaymentServiceImpl.java
  popi-payment-service/src/main/resources/application-local.yml
  popi-payment-service/src/main/resources/db/migration/V2__create_payment_item_table.sql
  popi-payment-service/src/main/resources/db/migration/V3__alter_payment_table_add_popup_id_column.sql
  popi-payment-service/src/test/java/com/lgcns/kafka/EmbeddedKafkaIntegrationTest.java
  popi-payment-service/src/test/java/com/lgcns/service/PaymentServiceTest.java
  popi-payment-service/src/test/resources/application-test.yml
Labels: ✨ feature

#72 feat: Google OAuth audiences에 iOS 클라이언트 ID 추가
  popi-auth-service/src/main/resources/application-local.yml
  popi-auth-service/src/test/resources/application-test.yml
Labels: ✨ feature

#74 feat: 상품 구매 Kafka 메시지 purchasedAt 필드 문자열 포맷으로 변경
  popi-payment-service/src/main/java/com/lgcns/kafka/message/ItemPurchasedMessage.java
Labels: ✨ feature

#75 fix: 결제 준비 시 merchantUid 길이 초과로 검증 실패하는 문제 수정
  popi-payment-service/src/main/java/com/lgcns/service/PaymentServiceImpl.java
  popi-payment-service/src/test/java/com/lgcns/service/PaymentServiceTest.java
Labels: 🐛 bug/error

#76 fix: 지도 기반 팝업 리스트 조회 API 엔드포인트 수정
  popi-popup-service/src/main/java/com/lgcns/externalApi/PopupController.java
Labels: 🐛 bug/error

#78 fix: 지도 기반 팝업 리스트 조회 응답 DTO 수정
  popi-popup-service/src/main/java/com/lgcns/client/managerClient/ManagerServiceClient.java
  popi-popup-service/src/main/java/com/lgcns/dto/response/PopupMapResponse.java
  popi-popup-service/src/main/java/com/lgcns/externalApi/PopupController.java
  popi-popup-service/src/main/java/com/lgcns/service/PopupService.java
  popi-popup-service/src/main/java/com/lgcns/service/PopupServiceImpl.java
  popi-popup-service/src/test/java/com/lgcns/service/PopupServiceTest.java
Labels: 🐛 bug/error

#77 feat: 예약 회원 입장 API 구현
  popi-api-gateway/src/main/resources/application-local.yml
  popi-reservation-service/build.gradle
  popi-reservation-service/src/main/java/com/lgcns/dto/request/QrEntranceInfoRequest.java
  popi-reservation-service/src/main/java/com/lgcns/event/handler/MemberReservationEventHandler.java
  popi-reservation-service/src/main/java/com/lgcns/exception/MemberReservationErrorCode.java
  popi-reservation-service/src/main/java/com/lgcns/externalApi/MemberReservationController.java
  popi-reservation-service/src/main/java/com/lgcns/kafka/config/KafkaProducerConfig.java
  popi-reservation-service/src/main/java/com/lgcns/kafka/message/MemberEnteredMessage.java
  popi-reservation-service/src/main/java/com/lgcns/kafka/producer/MemberEnteredProducer.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationService.java
  popi-reservation-service/src/main/java/com/lgcns/service/MemberReservationServiceImpl.java
  popi-reservation-service/src/main/resources/application-local.yml
  popi-reservation-service/src/test/java/com/lgcns/kafka/EmbeddedKafkaIntegrationTest.java
  popi-reservation-service/src/test/java/com/lgcns/service/MemberReservationServiceTest.java
  popi-reservation-service/src/test/resources/application-test.yml
Labels: ✨ feature
