Repository popi-official/popi-user-server, pull requests merged in 2025-04, with the labels that each got.

#1 chore: 프로젝트 초기 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/popi-ci.yml
  build.gradle
  popi-eureka-server/build.gradle
  popi-eureka-server/src/main/java/com/lgcns/popieurekaserver/PopiEurekaServerApplication.java
  popi-eureka-server/src/main/resources/application.yml
  popi-eureka-server/src/test/java/com/lgcns/popieurekaserver/PopiEurekaServerApplicationTests.java
  scripts/pre-commit
  settings.gradle
Labels: ⚙️ chore

#2 chore: 공통 응답 처리 어드바이스 생성
  popi-common/build.gradle
  popi-common/src/main/java/com/lgcns/PopiCommonApplication.java
  popi-common/src/main/java/com/lgcns/response/GlobalResponse.java
  popi-common/src/main/java/com/lgcns/response/GlobalResponseAdvice.java
  popi-common/src/test/java/com/lgcns/PopiCommonApplicationTests.java
  settings.gradle
Labels: ⚙️ chore

#3 feat: Config Server 설정
  .gitignore
  popi-config-server/build.gradle
  popi-config-server/src/main/java/com/lgcns/PopiConfigServerApplication.java
  popi-config-server/src/main/resources/application.yml
  popi-config-server/src/test/java/com/lgcns/PopiConfigServerApplicationTests.java
  popi-eureka-server/build.gradle
  popi-eureka-server/src/main/resources/application.yml
  popi-eureka-server/src/test/resources/application.yml
  settings.gradle
Labels: ✨ feature

#5 feat: Global Exception Handler 생성
  popi-common/src/main/java/com/lgcns/error/ErrorResponse.java
  popi-common/src/main/java/com/lgcns/error/GlobalExceptionHandler.java
  popi-common/src/main/java/com/lgcns/error/exception/CustomException.java
  popi-common/src/main/java/com/lgcns/error/exception/ErrorCode.java
  popi-common/src/main/java/com/lgcns/error/exception/GlobalErrorCode.java
  popi-common/src/main/java/com/lgcns/response/GlobalResponse.java
Labels: ✨ feature

#9 chore: Swagger 설정
  popi-api-gateway/build.gradle
  popi-config-server/build.gradle
Labels: ⚙️ chore

#6 chore: QueryDSL 설정
  popi-common/build.gradle
  popi-common/src/main/java/com/lgcns/config/QueryDslConfig.java
Labels: ⚙️ chore

#10 feat: BaseTimeEntity 생성
  popi-common/build.gradle
  popi-common/src/main/java/com/lgcns/config/JpaAuditingConfig.java
  popi-common/src/main/java/com/lgcns/model/BaseTimeEntity.java
Labels: ✨ feature

#12 feat: 회원 도메인 구현 및 Security 설정
  popi-auth-service/build.gradle
  popi-auth-service/src/main/java/com/lgcns/config/WebSecurityConfig.java
  popi-auth-service/src/main/java/com/lgcns/domain/Member.java
  popi-auth-service/src/main/java/com/lgcns/domain/MemberGender.java
  popi-auth-service/src/main/java/com/lgcns/domain/MemberRole.java
  popi-auth-service/src/main/java/com/lgcns/domain/MemberStatus.java
  popi-auth-service/src/main/java/com/lgcns/domain/OauthInfo.java
  popi-auth-service/src/main/java/com/lgcns/repository/MemberRepository.java
  popi-common/build.gradle
Labels: ✨ feature

#13 feat: 소셜 로그인 구현
  popi-auth-service/build.gradle
  popi-auth-service/src/main/java/com/lgcns/client/GoogleOauthClient.java
  popi-auth-service/src/main/java/com/lgcns/client/KakaoOauthClient.java
  popi-auth-service/src/main/java/com/lgcns/config/FeignConfig.java
  popi-auth-service/src/main/java/com/lgcns/config/SwaggerConfig.java
  popi-auth-service/src/main/java/com/lgcns/constants/SecurityConstants.java
  popi-auth-service/src/main/java/com/lgcns/controller/AuthController.java
  popi-auth-service/src/main/java/com/lgcns/domain/OauthProvider.java
  popi-auth-service/src/main/java/com/lgcns/domain/RefreshToken.java
  popi-auth-service/src/main/java/com/lgcns/dto/request/AuthCodeRequest.java
  popi-auth-service/src/main/java/com/lgcns/dto/response/IdTokenResponse.java
  popi-auth-service/src/main/java/com/lgcns/dto/response/SocialLoginResponse.java
  popi-auth-service/src/main/java/com/lgcns/exception/AuthErrorCode.java
  popi-auth-service/src/main/java/com/lgcns/repository/MemberRepository.java
  popi-auth-service/src/main/java/com/lgcns/repository/RefreshTokenRepository.java
  popi-auth-service/src/main/java/com/lgcns/service/AuthService.java
  popi-auth-service/src/main/java/com/lgcns/service/GoogleService.java
  popi-auth-service/src/main/java/com/lgcns/service/IdTokenVerifier.java
  popi-auth-service/src/main/java/com/lgcns/service/JwtTokenService.java
  popi-auth-service/src/main/java/com/lgcns/service/KakaoService.java
  popi-auth-service/src/main/java/com/lgcns/util/JwtUtil.java
  popi-common/build.gradle
Labels: ✨ feature

#14 refactor: ErrorCode 인터페이스 default 메서드 적용
  .github/PULL_REQUEST_TEMPLATE.md
  popi-auth-service/src/main/java/com/lgcns/exception/AuthErrorCode.java
  popi-common/src/main/java/com/lgcns/error/exception/ErrorCode.java
  popi-common/src/main/java/com/lgcns/error/exception/GlobalErrorCode.java
Labels: ♻️ refactor

#16 fix: Config Server Git URI 인증 정보 수정
  popi-config-server/src/main/resources/application.yml
Labels: 🐛 bug/error
